# Generated by Django 4.2.1 on 2023-06-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_files_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='pdf',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default='', upload_to='./'),
            preserve_default=False,
        ),
    ]
