# Generated by Django 4.2.1 on 2023-06-27 05:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=core.models.OverwriteStorage(), upload_to=''),
        ),
    ]
